const GameState = Object.freeze({
  TITLE: 'TITLE',
  LOBBY: 'LOBBY',
  COUNTDOWN: 'COUNTDOWN',
  PLAYING: 'PLAYING',
  RESULT: 'RESULT',
  CHEAT_DETECTED: 'CHEAT_DETECTED',
  TRAINING: 'TRAINING',
});

const NetMsg = Object.freeze({
  JOIN: 'join',
  WELCOME: 'welcome',
  PLAYER_JOINED: 'player_joined',
  PLAYER_LEFT: 'player_left',
  STATE: 'state',
  FIRE_REQUEST: 'fire_request',
  PROJ_SPAWN: 'proj_spawn',
  HIT: 'hit',
  HIT_EFFECT: 'hit_effect',
  EXPLOSION: 'explosion',
  AMMO_UPDATE: 'ammo_update',
  PLAYER_CORRECT: 'player_correct',
  RESPAWN: 'respawn',
  GAME_START: 'game_start',
  MAP_SELECT: 'map_select',
  GAME_OVER: 'game_over',
  RELOAD_COMPLETE: 'reload_complete',
  READY: 'ready',
  WEAPON_CHANGE: 'weapon_change',
  NAME_CHANGE: 'name_change',
  LOBBY_STATE: 'lobby_state',
  COUNTDOWN_SYNC: 'countdown_sync',
  GAME_TIMER: 'game_timer',
  RESULT_SYNC: 'result_sync',
  RETURN_LOBBY: 'return_lobby',
  KILL_FEED: 'kill_feed',
  RESPAWN_REQUEST: 'respawn_request',
  CHEAT_DETECTED: 'cheat_detected',
  INPUT: 'input',
  INPUT_ACK: 'input_ack',
  BEAM_FIRE: 'beam_fire',
  BEAM_EFFECT: 'beam_effect',
  PASSIVE_CHANGE: 'passive_change',
  HEALTH_UPDATE: 'health_update',
  SCORE_UPDATE: 'score_update',
  STATE_DIFF: 'state_diff',
  PING: 'ping',
  PONG: 'pong',
});
