const PASSIVE_DETAILS = {
  // ========== 移動 (Movement) ==========
  runner: {
    displayNameJa: "ランナー",
    descriptionEn: "Move speed +10%",
    descriptionJa: "移動速度が10%上昇する。全武器種に有効な基本の強化。",
    categoryJa: "移動",
    effect: "移動速度が10%増加する。スタック可能で、他の移動速度バフと乗算で適用される。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["積極的な位置取り", "常に動き回るヒット＆アウェイ"],
    merits: ["全ての武器構成と組み合わせやすい", "被弾率の低下につながる"],
    demerits: ["効果が地味で体感しづらい", "単体では劇的な変化を生まない"]
  },
  sprinter: {
    displayNameJa: "スプリンター",
    descriptionEn: "Dash speed +15%",
    descriptionJa: "ダッシュ速度が15%上昇する。接近戦での間合い詰めや回避性能が向上。",
    categoryJa: "移動",
    effect: "ダッシュ移動速度が15%増加する。より素早い接近と離脱が可能になる。",
    synergyWeapons: ["shotgun", "melee", "beamRifle"],
    antiSynergyWeapons: ["sniperRifle", "rocketLauncher"],
    recommendedPlaystyle: ["素早い接近と離脱", "アグレッシブな前衛戦術"],
    merits: ["敵の射線を高速で横切れる", "撃ち合い中の回避性能が向上"],
    demerits: ["操作が忙しくなる", "狭いマップでは効果が薄い"]
  },
  doubleJump: {
    displayNameJa: "ダブルジャンプ",
    descriptionEn: "Grants an extra jump",
    descriptionJa: "空中で追加の1回ジャンプが可能になる。高所への到達や空中での方向転換に役立つ。",
    categoryJa: "移動",
    effect: "空中でもう一度ジャンプできるようになる。高所へのアクセスや壁越えの機動性が大幅に向上する。",
    synergyWeapons: ["rocketLauncher", "shotgun", "smg"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["高所を活かした高低差攻撃", "予測不能な空中軌道"],
    merits: ["マップの探索範囲が広がる", "敵の照準を狂わせやすい"],
    demerits: ["操作に慣れが必要", "滞空時間が長くなり被弾リスクも増加"]
  },
  tripleJump: {
    displayNameJa: "トリプルジャンプ",
    descriptionEn: "Grants two extra jumps",
    descriptionJa: "空中で追加の2回ジャンプが可能になる。驚異的な空中機動を実現する。",
    categoryJa: "移動",
    effect: "空中で最大2回まで追加ジャンプできるようになる。通常では到達不可能な場所への移動や長期の空中戦が可能。",
    synergyWeapons: ["rocketLauncher", "shotgun", "sniperRifle"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["空中からの狙撃", "高高度からの奇襲攻撃"],
    merits: ["マップのほぼ全ての場所に到達可能", "空中での軌道変更が豊富"],
    demerits: ["滞空時間が長く被弾しやすい", "高度な操作技術が必要"]
  },
  wallRunner: {
    displayNameJa: "ウォールランナー",
    descriptionEn: "Run on walls",
    descriptionJa: "壁の上を走ることができる。立体的な機動が可能になり、戦術の幅が大きく広がる。",
    categoryJa: "移動",
    effect: "壁面に接触した状態で壁の上を走行できるようになる。壁走中は射撃も可能。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: ["sniperRifle", "rocketLauncher"],
    recommendedPlaystyle: ["壁を駆使した立体戦闘", "高所からの不意打ち"],
    merits: ["敵の予測不能な動きが可能", "射線を遮断しながら移動できる"],
    demerits: ["操作難易度が高い", "天井のない壁でのみ使用可能"]
  },
  airDash: {
    displayNameJa: "エアダッシュ",
    descriptionEn: "Dash while airborne",
    descriptionJa: "空中でもダッシュが可能になる。空中戦の機動性が飛躍的に向上する。",
    categoryJa: "移動",
    effect: "空中でのダッシュ移動が可能になる。エアダッシュ中は方向転換もでき、空中での回避性能が大幅に向上する。",
    synergyWeapons: ["shotgun", "beamRifle", "smg"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["空中での積極的な交戦", "ジャンプからの急接近･離脱"],
    merits: ["空中での被弾回避に優れる", "立体機動の幅が広がる"],
    demerits: ["接地時には効果がない", "スタミナ管理が必要"]
  },
  slideBoost: {
    displayNameJa: "スライドブースト",
    descriptionEn: "Sliding gives speed boost",
    descriptionJa: "スライディング中に移動速度が上昇する。素早い移動手段として活用できる。",
    categoryJa: "移動",
    effect: "スライディング開始時に短時間の速度上昇効果が発生する。スライド終了後も慣性が持続する。",
    synergyWeapons: ["shotgun", "smg", "pistol"],
    antiSynergyWeapons: ["sniperRifle", "rocketLauncher"],
    recommendedPlaystyle: ["スライドを活用した高速移動戦術", "低姿勢を保った接近戦"],
    merits: ["移動と回避を同時に行える", "スライド射撃との相性が良い"],
    demerits: ["スライド可能な地面でのみ有効", "長時間の使用には向かない"]
  },
  bunnyHopper: {
    displayNameJa: "バニーホッパー",
    descriptionEn: "Jumping while running preserves momentum",
    descriptionJa: "走行中のジャンプで慣性が維持される。高速移動を維持したまま跳躍できる。",
    categoryJa: "移動",
    effect: "走行中にジャンプしても速度が減衰しなくなる。連続ジャンプによる加速が可能になる。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: ["sniperRifle", "rocketLauncher"],
    recommendedPlaystyle: ["跳躍を交えた高速移動", "継続的な機動戦"],
    merits: ["一度加速すると止まりにくい", "他の移動系パッシブとの相性が抜群"],
    demerits: ["操作技術が大きく影響する", "急停止が難しくなる"]
  },

  // ========== 武器強化 (Weapon) ==========
  heavyHands: {
    displayNameJa: "ヘビーハンズ",
    descriptionEn: "Damage +10%",
    descriptionJa: "全ての武器の与ダメージが10%上昇する。シンプルかつ強力な火力強化。",
    categoryJa: "武器強化",
    effect: "武器の基礎ダメージが10%増加する。最終ダメージに対して乗算で適用され、他のダメージバフと重複する。",
    synergyWeapons: ["shotgun", "sniperRifle", "rocketLauncher"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["どの武器構成にも適合", "火力特化ビルドの基礎"],
    merits: ["全ての局面で腐らない", "計算が単純で組み合わせやすい"],
    demerits: ["単体の効果は控えめ", "他のバフと重ねないと実感しづらい"]
  },
  rapidFire: {
    displayNameJa: "ラピッドファイア",
    descriptionEn: "Fire rate +10%",
    descriptionJa: "武器の発射速度が10%上昇する。継続火力の底上げに貢献する。",
    categoryJa: "武器強化",
    effect: "全ての武器の発射間隔が10%短縮される。DPSが直接的に向上し、特に連射武器との相性が良い。",
    synergyWeapons: ["smg", "pistol", "beamRifle"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["連射武器との組み合わせ", "継続火力を重視したビルド"],
    merits: ["DPSを確実に向上させる", "連射武器と組み合わせると効果が倍増する"],
    demerits: ["弾薬消費が増加する", "単発武器には恩恵が少ない"]
  },
  quickReload: {
    displayNameJa: "クイックリロード",
    descriptionEn: "Reload 25% faster",
    descriptionJa: "リロード速度が25%向上する。戦闘中のダウンタイムを大幅に短縮する。",
    categoryJa: "武器強化",
    effect: "全ての武器のリロード時間が25%短縮される。リロードの長い武器ほど恩恵が大きく、戦闘継続能力が向上する。",
    synergyWeapons: ["shotgun", "sniperRifle", "rocketLauncher"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["リロードの長い武器と好相性", "持続火力を重視した戦術"],
    merits: ["リロード中の隙を減らせる", "弾を撃ち切るリスクが軽減される"],
    demerits: ["リロードのない武器には無意味", "過信は禁物"]
  },
  steadyAim: {
    displayNameJa: "ステディエイム",
    descriptionEn: "Recoil -25%",
    descriptionJa: "武器の反動が25%減少する。精密な射撃が可能になり、命中精度が向上する。",
    categoryJa: "武器強化",
    effect: "射撃時の反動（垂直・水平）が25%軽減される。連射時の照準のブレが抑えられ、より正確な射撃が可能になる。",
    synergyWeapons: ["smg", "rifle", "beamRifle"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["中～遠距離からの精密射撃", "連射武器の制御強化"],
    merits: ["連射武器の精度が大幅に向上", "遠距離戦での命中率が上がる"],
    demerits: ["反動の少ない武器では効果が薄い", "反動制御に慣れているほど実感しづらい"]
  },
  sharpshooter: {
    displayNameJa: "シャープシューター",
    descriptionEn: "Spread -20%",
    descriptionJa: "武器の拡散範囲が20%減少する。遠距離の命中精度が向上する。",
    categoryJa: "武器強化",
    effect: "射撃時の弾の拡散範囲が20%狭くなる。特に散弾武器や連射武器での精度向上に効果的。",
    synergyWeapons: ["shotgun", "smg", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["遠距離からの精密攻撃", "散弾武器の射程延伸"],
    merits: ["散弾銃の有効射程が伸びる", "遠距離の命中率が安定する"],
    demerits: ["近接戦闘では恩恵を実感しづらい", "一部の武器では効果が限定的"]
  },
  glassCannon: {
    displayNameJa: "グラスキャノン",
    descriptionEn: "Damage +25%, incoming damage +20%",
    descriptionJa: "与ダメージが25%上昇するが、被ダメージも20%増加する。ハイリスクハイリターンな強化。",
    categoryJa: "武器強化",
    effect: "与ダメージが25%増加する代わりに、受けるダメージも20%増加する。火力を追求する上級者向けのリスク型強化。",
    synergyWeapons: ["sniperRifle", "rocketLauncher", "shotgun"],
    antiSynergyWeapons: ["smg", "pistol"],
    recommendedPlaystyle: ["一撃離脱の火力特化", "被弾を前提としない完璧な立ち回り"],
    merits: ["火力上昇量が非常に大きい", "撃ち勝ちやすくなる"],
    demerits: ["被ダメージ増加が痛い", "防御系パッシブとの併用がほぼ必須"]
  },
  triggerHappy: {
    displayNameJa: "トリガーハッピー",
    descriptionEn: "Fire rate +20%",
    descriptionJa: "武器の発射速度が20%上昇する。継続火力を大幅に強化する。",
    categoryJa: "武器強化",
    effect: "全ての武器の発射間隔が20%短縮される。Rapid Fireより効果が強力で、連射速度が顕著に向上する。",
    synergyWeapons: ["smg", "pistol", "beamRifle"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["弾幕のような連射攻撃", "瞬間火力の最大化"],
    merits: ["DPSが大幅に向上する", "連射武器で特に効果を発揮"],
    demerits: ["弾薬消費が激しくなる", "反動制御が難しくなる場合がある"]
  },
  heavyBarrel: {
    displayNameJa: "ヘビーバレル",
    descriptionEn: "Projectile speed +30%, range +20%",
    descriptionJa: "弾速が30%、射程が20%向上する。遠距離戦での命中率と有効射程を延伸する。",
    categoryJa: "武器強化",
    effect: "投射物の飛行速度が30%上昇し、武器の有効射程が20%延長される。移動体への命中率も改善される。",
    synergyWeapons: ["sniperRifle", "rocketLauncher", "pistol"],
    antiSynergyWeapons: ["shotgun"],
    recommendedPlaystyle: ["遠距離狙撃特化", "中距離での先制攻撃"],
    merits: ["遠距離での命中率が向上", "射程外からの一方的な攻撃が可能"],
    demerits: ["近距離戦ではほぼ無意味", "散弾武器との相性が悪い"]
  },
  armorPiercing: {
    displayNameJa: "アーマーピアシング",
    descriptionEn: "Pierce +1 enemy",
    descriptionJa: "弾が敵を1体多く貫通する。複数の敵を同時に攻撃できるようになる。",
    categoryJa: "武器強化",
    effect: "投射物の貫通回数が1増加する。一直線に並んだ敵を複数貫通してダメージを与えられる。",
    synergyWeapons: ["sniperRifle", "rifle", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["敵の直線配置を意識した攻撃", "密集戦での効率的な殲滅"],
    merits: ["複数敵への同時攻撃が可能", "一直線上の敵を効率的に処理"],
    demerits: ["単体の敵には効果がない", "地形に阻まれると機能しない"]
  },
  highVelocity: {
    displayNameJa: "ハイベロシティ",
    descriptionEn: "Projectile speed +30%",
    descriptionJa: "弾速が30%上昇する。移動する敵への追従性が向上する。",
    categoryJa: "武器強化",
    effect: "全ての投射物の飛行速度が30%増加する。リードショットが不要になり命中率が安定する。",
    synergyWeapons: ["sniperRifle", "rocketLauncher", "pistol"],
    antiSynergyWeapons: ["shotgun"],
    recommendedPlaystyle: ["高速移動する敵への対処", "遠距離からの狙撃"],
    merits: ["動く敵に当てやすくなる", "遠距離までの弾の到達時間が短縮"],
    demerits: ["近距離では恩恵を感じにくい", "散弾銃では効果が限定的"]
  },
  hollowPoint: {
    displayNameJa: "ホローポイント",
    descriptionEn: "Critical damage +50%",
    descriptionJa: "クリティカルダメージが50%上昇する。クリティカルヒット時の火力を大幅に高める。",
    categoryJa: "武器強化",
    effect: "クリティカルヒット時のダメージ倍率が50%増加する。クリティカル率を上げるパッシブと組み合わせることで真価を発揮する。",
    synergyWeapons: ["sniperRifle", "pistol", "rifle"],
    antiSynergyWeapons: ["shotgun", "smg"],
    recommendedPlaystyle: ["クリティカル特化ビルド", "一発の重い武器との組み合わせ"],
    merits: ["クリティカル時の burst 火力が跳ね上がる", "狙撃武器との相性が極めて良い"],
    demerits: ["クリティカルが発生しないと無意味", "クリ率強化が別途必要"]
  },
  explosiveAmmo: {
    displayNameJa: "エクスプローシブアモ",
    descriptionEn: "Bullets explode on impact",
    descriptionJa: "弾が着弾時に爆発を起こす。範囲攻撃が可能になり、複数敵へのダメージ効率が向上する。",
    categoryJa: "武器強化",
    effect: "全ての弾丸が着弾時に小規模な爆発を起こすようになる。爆発は周囲の敵に範囲ダメージを与える。",
    synergyWeapons: ["rocketLauncher", "shotgun", "sniperRifle"],
    antiSynergyWeapons: ["beamRifle"],
    recommendedPlaystyle: ["密集した敵への範囲攻撃", "地形破壊を活用した戦術"],
    merits: ["範囲攻撃で複数敵を巻き込める", "隠れた敵への間接ダメージ"],
    demerits: ["至近距離での自爆に注意", "精密な射撃が必要な状況では邪魔になる"]
  },
  giantBullets: {
    displayNameJa: "ジャイアントバレッツ",
    descriptionEn: "Projectile size +50%",
    descriptionJa: "弾のサイズが50%大きくなる。命中判定が広がり、当てやすくなる。",
    categoryJa: "武器強化",
    effect: "全ての投射物の衝突判定サイズが50%拡大される。遠距離での僅かなエイムのズレを吸収できる。",
    synergyWeapons: ["shotgun", "smg", "pistol"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["命中率を補いたい場合", "広い判定を活かした弾幕攻撃"],
    merits: ["エイム精度のハードルが下がる", "散弾のヒット数が増える"],
    demerits: ["弾が視覚的に邪魔になる場合がある", "精密狙撃には逆効果"]
  },

  // ========== クリティカル (Critical) ==========
  luckyShot: {
    displayNameJa: "ラッキーショット",
    descriptionEn: "Critical hit chance +10%",
    descriptionJa: "クリティカルヒット発生率が10%上昇する。運が良ければ大ダメージを叩き出せる。",
    categoryJa: "クリティカル",
    effect: "全ての攻撃のクリティカル発生確率が10%加算される。他のクリティカル率上昇効果と合算で適用される。",
    synergyWeapons: ["sniperRifle", "pistol", "rifle"],
    antiSynergyWeapons: ["smg", "beamRifle"],
    recommendedPlaystyle: ["クリティカル特化ビルドの基盤", "高火力武器との組み合わせ"],
    merits: ["確率次第で大きなリターン", "クリダメ強化との相性が抜群"],
    demerits: ["確率に依存する不安定さ", "単体では劇的な効果を期待しにくい"]
  },
  deadeye: {
    displayNameJa: "デッドアイ",
    descriptionEn: "Critical damage +50%",
    descriptionJa: "クリティカルダメージが50%上昇する。一撃の重みを増す強化。",
    categoryJa: "クリティカル",
    effect: "クリティカルヒットのダメージ倍率が50%増加する。基礎クリティカルダメージが高い武器ほど効果が大きい。",
    synergyWeapons: ["sniperRifle", "pistol", "rifle"],
    antiSynergyWeapons: ["smg", "beamRifle"],
    recommendedPlaystyle: ["一撃必殺を狙う狙撃スタイル", "クリティカル特化の火力特化"],
    merits: ["クリティカルの burst ダメージが強力", "高倍率武器との相性が良い"],
    demerits: ["クリティカルが前提のビルドが必要", "安定性に欠ける"]
  },
  executioner: {
    displayNameJa: "エクスキューショナー",
    descriptionEn: "+30% damage to enemies below 30% HP",
    descriptionJa: "HPが30%以下の敵へのダメージが30%上昇する。トドメを刺す能力が飛躍的に向上する。",
    categoryJa: "クリティカル",
    effect: "残りHPが最大HPの30%以下の敵に対する与ダメージが30%増加する。瀕死の敵を迅速に処理する。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["敵のHPを削った後の仕上げ役", "ハイペースな戦闘スタイル"],
    merits: ["瀕死の敵を確実に始末できる", "キル確定力が大幅に向上"],
    demerits: ["HPが多い相手には効果がない", "単独でのキル性能は変わらない"]
  },

  // ========== 投射物 (Projectile) ==========
  ricochetExpert: {
    displayNameJa: "リコシェエキスパート",
    descriptionEn: "Ricochet +1",
    descriptionJa: "弾が壁などに当たった時に跳ね返る回数が1回増加する。跳弾を活用した戦術が可能になる。",
    categoryJa: "投射物",
    effect: "投射物の跳弾可能回数が1増加する。壁や障害物に当たった弾が反射し、死角の敵にもダメージを与えられる。",
    synergyWeapons: ["pistol", "rifle", "smg"],
    antiSynergyWeapons: ["rocketLauncher", "shotgun"],
    recommendedPlaystyle: ["壁際の敵への間接攻撃", "角度を読んだテクニカルな射撃"],
    merits: ["遮蔽物の裏の敵を攻撃できる", "複数回の反射で広範囲をカバー"],
    demerits: ["操作が予測しづらい", "広い空間では効果が薄い"]
  },
  doubleRicochet: {
    displayNameJa: "ダブルリコシェ",
    descriptionEn: "Ricochet +2",
    descriptionJa: "弾が跳ね返る回数が2回増加する。複雑な跳弾軌道で敵を翻弄する。",
    categoryJa: "投射物",
    effect: "投射物の跳弾可能回数が2増加する。複数回の反射により、入り組んだ地形で驚異的な効果を発揮する。",
    synergyWeapons: ["pistol", "smg", "rifle"],
    antiSynergyWeapons: ["rocketLauncher", "shotgun"],
    recommendedPlaystyle: ["屋内や狭いマップでの戦闘", "跳弾を駆使したトリッキーな攻撃"],
    merits: ["複雑な地形での攻撃範囲が広大", "敵の予想外の角度から攻撃可能"],
    demerits: ["制御が難しく状況を選ぶ", "跳弾に頼りすぎると安定性を欠く"]
  },
  piercingRounds: {
    displayNameJa: "ピアシングラウンズ",
    descriptionEn: "Pierce +1 enemy",
    descriptionJa: "弾が敵を1体多く貫通する。複数の敵を一列に攻撃できる。",
    categoryJa: "投射物",
    effect: "投射物が貫通可能な敵の数が1増加する。最大2体の敵を貫通してダメージを与えられる。",
    synergyWeapons: ["sniperRifle", "rifle", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["敵陣を貫く一撃", "密集戦での効率的なダメージ稼ぎ"],
    merits: ["複数の敵への同時攻撃", "直線上の敵を効率的に処理"],
    demerits: ["単体相手では効果がない", "障害物が多いと活かしづらい"]
  },
  piercingShot: {
    displayNameJa: "ピアシングショット",
    descriptionEn: "Pierce +2 enemies",
    descriptionJa: "弾が敵を2体多く貫通する。最大3体までの敵を一気に貫く強力な貫通効果。",
    categoryJa: "投射物",
    effect: "投射物が貫通可能な敵の数が2増加する。最大3体の敵を一直線に貫通する。",
    synergyWeapons: ["sniperRifle", "rifle", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["密集した敵集団の一掃", "敵の配置を読んだ狙撃"],
    merits: ["多数の敵への同時攻撃が強力", "弾1発の価値が大幅に向上"],
    demerits: ["状況を選ぶ効果", "ボス戦などではほぼ無意味"]
  },
  clusterRound: {
    displayNameJa: "クラスターラウンド",
    descriptionEn: "Bullets split into 3 on hit",
    descriptionJa: "弾が命中時に3つに分裂する。範囲攻撃と追加ダメージを同時に実現する。",
    categoryJa: "投射物",
    effect: "弾が敵または壁に命中した際に3つの小型弾に分裂する。分裂した弾はそれぞれ別の敵や周囲に飛散する。",
    synergyWeapons: ["shotgun", "sniperRifle", "rocketLauncher"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["範囲火力重視のビルド", "散弾銃との相性が特に良い"],
    merits: ["命中時の追加攻撃が強力", "範囲攻撃としても機能する"],
    demerits: ["分裂弾の制御は困難", "分裂後の威力が低下する場合がある"]
  },
  chainLightning: {
    displayNameJa: "チェーンライトニング",
    descriptionEn: "Hits chain to 2 nearby enemies",
    descriptionJa: "命中した敵から近くの敵2体に電撃が連鎖する。範囲チェーンダメージを与える。",
    categoryJa: "投射物",
    effect: "攻撃が命中した敵から、周囲の敵2体まで電撃が連鎖する。連鎖先には元のダメージの一部が伝播する。",
    synergyWeapons: ["smg", "pistol", "beamRifle"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["敵が密集した場所での戦闘", "複数敵への拡散ダメージ"],
    merits: ["敵集団に対する高い殲滅力", "連鎖による予想外のキルが発生"],
    demerits: ["単体の敵には効果がない", "連鎖距離に制限がある"]
  },
  freezeBullet: {
    displayNameJa: "フリーズバレット",
    descriptionEn: "Slows enemies on hit",
    descriptionJa: "命中した敵の動きを鈍らせる。敵の接近を防ぎ、有利な距離を保てる。",
    categoryJa: "投射物",
    effect: "攻撃が命中した敵に減速効果を与える。効果時間中は敵の移動速度が低下する。",
    synergyWeapons: ["smg", "pistol", "sniperRifle"],
    antiSynergyWeapons: ["rocketLauncher"],
    recommendedPlaystyle: ["減速を活かした距離操作", "足の遅い敵を確実に仕留める"],
    merits: ["敵の接近を抑制できる", "射撃精度の向上に貢献"],
    demerits: ["減速耐性を持つ敵には無効", "ダメージそのものは増加しない"]
  },
  incendiary: {
    displayNameJa: "インセンダリー",
    descriptionEn: "Burns enemies on hit",
    descriptionJa: "命中した敵を炎上させ、追加の継続ダメージを与える。時間経過で徐々にHPを削る。",
    categoryJa: "投射物",
    effect: "攻撃が命中した敵を炎上状態にする。炎上中は継続的にダメージを受ける。",
    synergyWeapons: ["smg", "pistol", "shotgun"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["継続ダメージでじわじわと削る", "ヒット＆アウェイとの組み合わせ"],
    merits: ["時間経過で追加ダメージ", "敵の回復効果を妨害"],
    demerits: ["効果が表れるまで時間がかかる", "炎上ダメージは重複しない"]
  },
  poisonBullet: {
    displayNameJa: "ポイズンバレット",
    descriptionEn: "Poisons enemies on hit",
    descriptionJa: "命中した敵に毒を付与する。毒ダメージで継続的にHPを奪う。",
    categoryJa: "投射物",
    effect: "攻撃が命中した敵を毒状態にする。毒は時間経過でダメージを与え、効果は重積可能。",
    synergyWeapons: ["smg", "pistol", "shotgun"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["毒の重複を活かした持続火力", "体力の多い敵への対抗手段"],
    merits: ["重複可能な継続ダメージ", "持久戦でのダメージ効率が高い"],
    demerits: ["即効性に欠ける", "毒耐性を持つ敵には無効"]
  },

  // ========== ビーム (Beam) ==========
  wideBeam: {
    displayNameJa: "ワイドビーム",
    descriptionEn: "Beam width +50%",
    descriptionJa: "ビームの横幅が50%拡大する。命中判定が広がり、複数の敵を捉えやすくなる。",
    categoryJa: "ビーム",
    effect: "ビーム武器の当たり判定の幅が50%拡大される。複数の敵を同時に攻撃できる。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["複数敵への同時攻撃", "広い射線を活かした制圧射撃"],
    merits: ["命中率が大幅に向上", "密集した敵への効率が良い"],
    demerits: ["単体攻撃力は変わらない", "狭い通路では冗長になる"]
  },
  longBeam: {
    displayNameJa: "ロングビーム",
    descriptionEn: "Beam range +30%",
    descriptionJa: "ビームの射程距離が30%延長される。遠距離からのビーム攻撃が可能になる。",
    categoryJa: "ビーム",
    effect: "ビーム武器の最大射程が30%延長される。遠距離の敵を安全な位置から攻撃できる。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["後方からの支援射撃", "遠距離からの継続ダメージ"],
    merits: ["安全な距離から攻撃可能", "広いマップでの有効性が高い"],
    demerits: ["近距離戦では不要な強化", "ビーム以外の武器には無意味"]
  },
  beamOvercharge: {
    displayNameJa: "ビームオーバーチャージ",
    descriptionEn: "Beam damage +25%",
    descriptionJa: "ビーム武器のダメージが25%上昇する。ビーム特化ビルドの中核を担う強化。",
    categoryJa: "ビーム",
    effect: "ビーム武器の与ダメージが25%増加する。ビーム系パッシブの中でも特に火力に直結する。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["ビーム火力特化", "一點突破の火力重視"],
    merits: ["ビームビルドの核となる強化", "単純明快で強力"],
    demerits: ["ビーム武器以外では効果がない", "他の武器との併用時に腐る"]
  },
  beamReflection: {
    displayNameJa: "ビームリフレクション",
    descriptionEn: "Beam reflects off walls once",
    descriptionJa: "ビームが壁に当たると1回反射する。角度を利用した戦術的な射撃が可能。",
    categoryJa: "ビーム",
    effect: "ビームが壁や障害物に接触した際に1回だけ反射するようになる。反射後もダメージは維持される。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["入り組んだ地形での戦闘", "反射を読んだ高度な射撃"],
    merits: ["遮蔽物越しの攻撃が可能", "角度次第で予想外のヒット"],
    demerits: ["反射角の計算が必要", "広い空間では効果が限定的"]
  },
  energyMaster: {
    displayNameJa: "エナジーマスター",
    descriptionEn: "Beam range +20%, damage +15%",
    descriptionJa: "ビームの射程が20%、ダメージが15%上昇する。バランスよくビーム性能を強化する。",
    categoryJa: "ビーム",
    effect: "ビーム武器の射程を20%、ダメージを15%それぞれ向上させる。攻撃力と射程を同時に強化する万能型強化。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["全方位バランス型ビームビルド", "中距離でのビーム戦"],
    merits: ["射程と火力を同時に強化", "無駄のない効率的な強化"],
    demerits: ["特化型と比べると数値が控えめ", "ビーム以外では効果なし"]
  },
  plasmaOverload: {
    displayNameJa: "プラズマオーバーロード",
    descriptionEn: "Plasma explosion radius +30%",
    descriptionJa: "プラズマ爆発の範囲が30%拡大する。範囲攻撃性能が大幅に向上する。",
    categoryJa: "ビーム",
    effect: "プラズマ系武器の爆発半径が30%拡大される。より多くの敵を巻き込める。",
    synergyWeapons: ["plasmaCannon"],
    antiSynergyWeapons: ["beamRifle"],
    recommendedPlaystyle: ["範囲殲滅を重視した戦術", "プラズマ武器と組み合わせた制圧"],
    merits: ["範囲攻撃のカバー面積が拡大", "複数敵へのダメージ効率が向上"],
    demerits: ["プラズマ武器以外には効果がない", "爆発の巻き込みに注意"]
  },
  beamStabilizer: {
    displayNameJa: "ビームスタビライザー",
    descriptionEn: "Beam spread -30%",
    descriptionJa: "ビームの拡散範囲が30%減少する。より精密なビーム射撃が可能。",
    categoryJa: "ビーム",
    effect: "ビーム武器の拡散範囲が30%狭くなる。長距離射撃時のビームの収束性が向上する。",
    synergyWeapons: ["beamRifle"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["精密なビーム射撃", "長距離狙撃ビーム"],
    merits: ["遠距離での精度が向上", "DPSの無駄が減る"],
    demerits: ["近距離では恩恵が薄い", "プラズマ武器との相性が悪い"]
  },
  coolingSystem: {
    displayNameJa: "クーリングシステム",
    descriptionEn: "Beam fire interval -20%",
    descriptionJa: "ビームの発射間隔が20%短縮される。連続射撃性能が向上する。",
    categoryJa: "ビーム",
    effect: "ビーム武器の発射インターバルが20%短縮される。より高い継続火力を実現する。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["継続火力を重視したビーム戦", "オーバーヒート管理との両立"],
    merits: ["ビームのDPSが直接向上", "プラズマ武器の連射性も向上"],
    demerits: ["ビーム武器以外では効果がない", "オーバーヒートが早まる可能性"]
  },

  // ========== 生存 (Survival) ==========
  survivor: {
    displayNameJa: "サバイバー",
    descriptionEn: "HP +20",
    descriptionJa: "最大HPが20増加する。シンプルながら安定した生存力向上をもたらす。",
    categoryJa: "生存",
    effect: "最大HPが20ポイント増加する。基礎HPに対する固定値上昇で、被弾時の余裕が生まれる。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["どのビルドにも適合する汎用性", "初心者から上級者まで安定した強化"],
    merits: ["全ての局面で有効", "他の生存系パッシブと好相性"],
    demerits: ["効果が地味で実感しづらい", "%増加と比べると伸びが限定的"]
  },
  regeneration: {
    displayNameJa: "リジェネレーション",
    descriptionEn: "Slowly heal out of combat",
    descriptionJa: "非戦闘時にHPが徐々に回復する。戦闘と戦闘の間の立て直しが容易になる。",
    categoryJa: "生存",
    effect: "戦闘状態から一定時間経過後に自動HP回復が発動する。回復量は緩やか。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["持久戦を意識した戦い方", "ヒット＆アウェイ後の回復"],
    merits: ["ヒーリングアイテムの節約になる", "長期的な生存率が向上"],
    demerits: ["戦闘中は効果がない", "回復速度が遅く緊急時に頼れない"]
  },
  regenerationPlus: {
    displayNameJa: "リジェネレーション+",
    descriptionEn: "Faster out-of-combat healing",
    descriptionJa: "非戦闘時のHP回復速度が上昇する。素早い戦線復帰が可能になる。",
    categoryJa: "生存",
    effect: "非戦闘時の自動HP回復速度が通常のリジェネレーションより大幅に向上する。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["積極的な戦闘参加と離脱の反復", "ハイペースな戦闘スタイル"],
    merits: ["戦線復帰が非常に早い", "継続的な戦闘参加が可能"],
    demerits: ["戦闘中は効果がない", "瞬間的な回復手段にはならない"]
  },
  ironSkin: {
    displayNameJa: "アイアンスキン",
    descriptionEn: "Explosion damage -20%",
    descriptionJa: "爆発によるダメージを20%軽減する。爆発物対策に特化した防御強化。",
    categoryJa: "生存",
    effect: "爆発属性の攻撃から受けるダメージを20%軽減する。グレネードやロケットランチャーなどの爆発兵器に対する耐性が向上する。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["爆発物の多い環境での戦闘", "前線での積極的な戦闘"],
    merits: ["爆発兵器への耐性が向上", "範囲攻撃の被弾時のダメージ軽減"],
    demerits: ["非爆発攻撃には効果がない", "特定の状況以外では腐りやすい"]
  },
  medic: {
    displayNameJa: "メディック",
    descriptionEn: "Faster respawn healing",
    descriptionJa: "リスポーン時の回復が高速化する。復帰後の戦闘準備が素早く完了する。",
    categoryJa: "生存",
    effect: "リスポーン後に適用される回復効果の速度が上昇する。復帰直後の無防備な時間を短縮できる。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["デスマッチやチーム戦での生存重視", "リスキーなプレイスタイルの保険"],
    merits: ["復帰後すぐに戦闘に参加できる", "デスが多くなる状況ほど価値が高い"],
    demerits: ["死なない立ち回りでは無駄になる", "1ラウンドのデス数が少ないと効果が薄い"]
  },
  shieldGenerator: {
    displayNameJa: "シールドジェネレーター",
    descriptionEn: "50% damage reduction for 3s after respawn",
    descriptionJa: "リスポーン後3秒間、被ダメージを50%軽減する。復帰直後の安全を確保する。",
    categoryJa: "生存",
    effect: "リスポーン直後から3秒間、受けるダメージが50%軽減される。復帰後の安全な位置取りが可能。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["復帰直後のカウンター攻撃", "積極的な復帰後のポジショニング"],
    merits: ["復帰直後の被弾リスクを大幅に軽減", "逆転のチャンスを作りやすい"],
    demerits: ["効果時間が短い", "一度のリスポーンでしか発動しない"]
  },
  juggernaut: {
    displayNameJa: "ジャガーノート",
    descriptionEn: "Max HP +50",
    descriptionJa: "最大HPが50増加する。前線での耐久力が飛躍的に向上する。",
    categoryJa: "生存",
    effect: "最大HPが50ポイント増加する。大幅なHP増加により、一撃では倒されにくくなる。",
    synergyWeapons: ["shotgun", "smg"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["前線で弾を受け止めるタンク役", "近距離での撃ち合い重視"],
    merits: ["耐久力が大幅に向上", "近距離戦での強気なトレードが可能"],
    demerits: ["HPが多いほど効果が相対的に低下", "回復アイテムの効率が実質的に低下"]
  },
  nanoArmor: {
    displayNameJa: "ナノアーマー",
    descriptionEn: "Incoming damage -10%",
    descriptionJa: "受ける全てのダメージを10%軽減する。汎用的なダメージ軽減効果。",
    categoryJa: "生存",
    effect: "全ての属性の被ダメージを10%軽減する。あらゆる攻撃に対して一律の軽減が適用される万能な防御効果。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["どのビルドにも適合する防御強化", "被弾の多い前衛スタイル"],
    merits: ["全属性のダメージを軽減", "他の防御系パッシブと重積可能"],
    demerits: ["効果量が控えめ", "複数積まないと実感しづらい"]
  },
  emergencyShield: {
    displayNameJa: "エマージェンシーシールド",
    descriptionEn: "Gain shield when HP drops below 20%",
    descriptionJa: "HPが20%以下になった時にシールドが展開される。窮地を脱するためのセーフティネット。",
    categoryJa: "生存",
    effect: "HPが最大HPの20%を下回った際に、一定量のダメージを吸収するシールドが自動展開される。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["リスキーなトレードを仕掛ける戦術", "ピンチからの逆転を狙う"],
    merits: ["瀕死時の生存率が大きく向上", "不意の一撃を防げる"],
    demerits: ["一度発動すると長時間のクールダウン", "HP20%以下にならないと発動しない"]
  },
  vampire: {
    displayNameJa: "ヴァンパイア",
    descriptionEn: "Heal 5% of damage dealt",
    descriptionJa: "与ダメージの5%をHPとして吸収する。攻撃しながら回復できる強力な継戦効果。",
    categoryJa: "生存",
    effect: "敵に与えたダメージの5%をHPとして回復する。火力が高いほど回復量も増加する。",
    synergyWeapons: ["smg", "shotgun", "beamRifle"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["攻撃的な継戦スタイル", "火力特化ビルドの防御的補完"],
    merits: ["攻撃しながら回復できる", "火力が高いほど回復量が増える"],
    demerits: ["吸収量が少なく緊急時の回復には不向き", "ダメージを与えられないと無意味"]
  },

  // ========== ユーティリティ (Utility) ==========
  engineer: {
    displayNameJa: "エンジニア",
    descriptionEn: "Reload repairs deployables",
    descriptionJa: "リロード時に設置型デバイスを修理する。メカニクスを活かした戦術を支援する。",
    categoryJa: "ユーティリティ",
    effect: "武器のリロードを行うたびに、周囲にある味方の設置型デバイス（タレット・バリアなど）を修理する。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["設置デバイスを活用した防衛戦術", "チームプレイ重視のサポート"],
    merits: ["デバイスの延命が可能", "チーム全体の戦術幅が広がる"],
    demerits: ["デバイスを使用しない構成では無意味", "単独では効果を発揮しにくい"]
  },
  ammoPrinter: {
    displayNameJa: "アモプリンター",
    descriptionEn: "Regenerate ammo over time",
    descriptionJa: "時間経過で弾薬が自動回復する。弾切れの心配が減り、戦闘継続能力が向上する。",
    categoryJa: "ユーティリティ",
    effect: "時間経過に応じて弾薬が自動で回復する。長期戦での弾薬切れリスクを軽減する。",
    synergyWeapons: ["smg", "beamRifle", "shotgun"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["弾薬消費の激しい武器との組み合わせ", "長期戦を前提とした戦術"],
    merits: ["弾切れのリスクが減少", "リロード頻度が減り戦闘に集中できる"],
    demerits: ["回復速度が遅い", "瞬時の弾薬補給にはならない"]
  },
  quickHands: {
    displayNameJa: "クイックハンズ",
    descriptionEn: "Weapon switch speed +30%",
    descriptionJa: "武器の切り替え速度が30%上昇する。状況に応じた武器変更がスムーズになる。",
    categoryJa: "ユーティリティ",
    effect: "武器の持ち替えモーション時間が30%短縮される。複数の武器を状況に応じて使い分ける戦術の反応速度が向上する。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["複数武器の併用スタイル", "状況に応じた武器切り替えを重視"],
    merits: ["武器変更がスムーズになる", "戦術の切り替えが迅速になる"],
    demerits: ["単一武器しか使わない場合は不要", "効果が地味"]
  },
  radar: {
    displayNameJa: "レーダー",
    descriptionEn: "Show enemy positions on minimap",
    descriptionJa: "ミニマップに敵の位置が表示されるようになる。索敵能力が大幅に向上する。",
    categoryJa: "ユーティリティ",
    effect: "ミニマップ上に敵の現在位置が常時表示されるようになる。隠れている敵や遠距離の敵の位置を把握できる。",
    synergyWeapons: ["sniperRifle", "rocketLauncher"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["情報を活かした先読み戦術", "スナイパーや遠距離火力との好相性"],
    merits: ["敵の位置を常に把握可能", "待ち伏せを事前に回避できる"],
    demerits: ["直接的な戦闘力向上にはならない", "敵の行動が読めないと情報が活かせない"]
  },
  sixthSense: {
    displayNameJa: "シックスセンス",
    descriptionEn: "Warning when enemies are nearby",
    descriptionJa: "近くに敵がいる時に警告が表示される。接近する敵への対応が容易になる。",
    categoryJa: "ユーティリティ",
    effect: "一定範囲内に敵が接近した際に警告エフェクトが発生する。奇襲や不意打ちを事前に察知できる。",
    synergyWeapons: ["shotgun", "smg"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["近距離での反応速度を活かした戦術", "待ち伏せ防止"],
    merits: ["不意打ちへの耐性が向上", "接近戦での判断材料になる"],
    demerits: ["遠距離の敵には反応しない", "警告に頼りすぎると逆に隙ができる"]
  },
  fastHands: {
    displayNameJa: "ファストハンズ",
    descriptionEn: "Weapon switch speed +30%",
    descriptionJa: "武器の切り替え速度が30%上昇する。戦闘中の武器変更を素早く行える。",
    categoryJa: "ユーティリティ",
    effect: "武器切り替えモーションが30%短縮される。Quick Handsと同等の効果。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["複数武器を駆使したコンバット", "素早い武器変更を活かした戦術"],
    merits: ["状況に合わせた武器変更が迅速に", "戦闘の流れを止めない"],
    demerits: ["単一武器運用では不要", "効果が目立ちにくい"]
  },
  tracker: {
    displayNameJa: "トラッカー",
    descriptionEn: "Mark enemies on hit",
    descriptionJa: "攻撃が命中した敵をマークする。マークした敵の位置を一定時間視認できる。",
    categoryJa: "ユーティリティ",
    effect: "攻撃を命中させた敵が自動的にマーキングされる。マークされた敵は壁越しでも位置が可視化される。",
    synergyWeapons: ["sniperRifle", "rifle", "smg"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["チーム連携を重視した戦術", "敵の動きを常に把握したい場合"],
    merits: ["マークした敵の位置を追跡可能", "チーム全体に情報共有される"],
    demerits: ["直接的な戦闘力強化ではない", "命中させ続けないと効果が切れる"]
  },

  // ========== 弾薬 (Ammo) ==========
  extraMagazine: {
    displayNameJa: "エクストラマガジン",
    descriptionEn: "Magazine size +30%",
    descriptionJa: "マガジン容量が30%増加する。リロード頻度が減り、継続火力が向上する。",
    categoryJa: "弾薬",
    effect: "全ての武器のマガジン容量が30%増加する。1回のリロードあたりの継続射撃時間が延びる。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["リロード頻度を減らしたい場合", "連射武器との組み合わせ"],
    merits: ["継続火力が向上", "リロードの手間が減る"],
    demerits: ["マガジンのない武器には無意味", "リロード速度自体は変わらない"]
  },
  scavenger: {
    displayNameJa: "スカベンジャー",
    descriptionEn: "Restore ammo on kill",
    descriptionJa: "敵を倒すと弾薬が回復する。キルを重ねることで弾切れの心配がなくなる。",
    categoryJa: "弾薬",
    effect: "敵をキルするたびに一定量の弾薬が回復する。連続キルによって弾薬を補充しながら戦闘を継続できる。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["積極的にキルを重ねる攻撃的スタイル", "弾薬消費の激しい武器との組み合わせ"],
    merits: ["弾薬管理のストレスが軽減", "連戦での継戦能力が高い"],
    demerits: ["キルが取れないと機能しない", "ボス戦などでは無価値"]
  },
  efficient: {
    displayNameJa: "エフィシェント",
    descriptionEn: "Ammo consumption -10%",
    descriptionJa: "弾薬消費量が10%減少する。同じ弾薬でより多くの攻撃が可能になる。",
    categoryJa: "弾薬",
    effect: "射撃時の弾薬消費量が10%減少する。実質的な弾薬効率が向上する。",
    synergyWeapons: ["smg", "shotgun", "beamRifle"],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["弾薬効率を重視した経済的な戦闘", "長期戦を見据えたビルド"],
    merits: ["弾薬の持続時間が延びる", "実質的な火力増加につながる"],
    demerits: ["効果が地味で実感しづらい", "弾薬無限の武器には無意味"]
  },

  // ========== アルティメット (Ultimate) ==========
  berserker: {
    displayNameJa: "バーサーカー",
    descriptionEn: "Kill grants 5s of +25% damage and +20% speed",
    descriptionJa: "キルを取ると5秒間、ダメージ+25%、移動速度+20%のバフを得る。連続キルで無双状態に突入する。",
    categoryJa: "アルティメット",
    effect: "敵をキルするたびに5秒間、与ダメージ25%増加＆移動速度20%増加のバフ効果が発動する。効果中にさらにキルを取ると持続時間がリセットされる。",
    synergyWeapons: ["shotgun", "smg", "pistol"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["連続キルを狙うアグレッシブスタイル", "接近戦での無双状態"],
    merits: ["キル連鎖で圧倒的な強化状態に", "火力と機動性を同時に強化"],
    demerits: ["キルできないと全く効果がない", "効果時間が短くリセットが必要"]
  },
  adrenaline: {
    displayNameJa: "アドレナリン",
    descriptionEn: "Below 30% HP: +20% damage, +15% speed",
    descriptionJa: "HPが30%以下の時、ダメージ+20%、移動速度+15%のバフを得る。窮地からの逆転を可能にする。",
    categoryJa: "アルティメット",
    effect: "HPが最大HPの30%以下の状態の間、与ダメージが20%増加し、移動速度が15%上昇する。",
    synergyWeapons: ["shotgun", "smg"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["ギリギリの体力管理を活かした逆転戦術", "リスクを取った攻め"],
    merits: ["ピンチでの火力が大幅に向上", "逆転の可能性を高める"],
    demerits: ["HP30%以下の危険な状態が前提", "一撃で倒されると無意味"]
  },
  timeWarp: {
    displayNameJa: "タイムワープ",
    descriptionEn: "Kills reduce cooldowns by 1s",
    descriptionJa: "キルを取るたびに全てのクールダウンが1秒短縮される。スキル回転率が飛躍的に向上する。",
    categoryJa: "アルティメット",
    effect: "敵をキルするたびに、全てのアビリティとアイテムの残りクールダウンが1秒減少する。",
    synergyWeapons: ["smg", "shotgun", "pistol"],
    antiSynergyWeapons: ["sniperRifle"],
    recommendedPlaystyle: ["スキル主体のビルドとの組み合わせ", "クールダウンの長い強力スキルを多用"],
    merits: ["スキルの回転率が大幅に向上", "クールダウン管理の自由度が上がる"],
    demerits: ["キルが取れないと効果がない", "スキルの少ないビルドでは恩恵が薄い"]
  },
  overclock: {
    displayNameJa: "オーバークロック",
    descriptionEn: "Every 10s: beam power surges for 3s",
    descriptionJa: "10秒ごとにビームが3秒間パワーサージする。ビーム武器の瞬間火力を飛躍的に高める。",
    categoryJa: "アルティメット",
    effect: "10秒間隔で自動的にビーム武器が3秒間のオーバークロック状態になる。効果中はビームのダメージと射程が大幅に上昇する。",
    synergyWeapons: ["beamRifle", "plasmaCannon"],
    antiSynergyWeapons: ["shotgun", "sniperRifle"],
    recommendedPlaystyle: ["ビーム武器特化のタイミング重視ビルド", "サージ中の burst 火力を活かす"],
    merits: ["定期的な burst ダメージが強力", "ビームビルドの中核的存在"],
    demerits: ["ビーム武器以外では完全に無意味", "タイミング管理が必要"]
  },
  phaseShift: {
    displayNameJa: "フェーズシフト",
    descriptionEn: "Take no damage for 1s after taking lethal damage",
    descriptionJa: "致命傷を受けた後1秒間、一切のダメージを受けなくなる。死を回避する最後の切り札。",
    categoryJa: "アルティメット",
    effect: "致命的なダメージを受けた際に自動発動し、その後1秒間無敵状態になる。発動後はクールダウンが発生する。",
    synergyWeapons: [],
    antiSynergyWeapons: [],
    recommendedPlaystyle: ["リスキーなプレイのセーフティネット", "あえて被弾を誘う戦術"],
    merits: ["死を一度だけ回避できる", "逆転のチャンスを生み出す"],
    demerits: ["長時間のクールダウンが必要", "連続した致命傷には対応できない"]
  }
};